version = 1

[[annotations]]
path = [
    "README.md",
    "src/metadata.json",
    ".clang-format"
]
SPDX-FileCopyrightText = "Copyright (c) 2022 MBition GmbH."
SPDX-License-Identifier = "GPL-2.0-or-later"
